
#ifndef LUNDGREN_CONSTANTS
#define LUNDGREN_CONSTANTS

#define INTERIM_TABLE_ENGINE "ENGINE = MEMORY"

#define PLUGIN_FLAG "/*histogram*/"
#define UPDATE_INTERVAL 200000


#endif  // LUNDGREN_CONSTANTS